module.exports = {
    firebaseConfig: {
        apiKey: "", // coloque sua api key aqui
        authDomain: "", // ... auth domain ...
        databaseURL: "", // ... database url ...
        projectId: "", // ... projectid ...
        storageBucket: "", // ... storagebucket ...
        messagingSenderId: "", // ... messagingSenderId ...
        appId: "", // ... appId ...
        measurementId: "" // ... measurementId ...
    },
    prefix: "", // coloque aqui o prefix do seu bot
    token: "", // aqui coloque o token do bot para o bot ficar online
    intents: ['GUILDS', 'GUILD_PRESENCES',  'GUILD_MESSAGES' , 'GUILD_MEMBERS', 'GUILD_BANS','GUILD_EMOJIS', 'GUILD_MESSAGE_REACTIONS', 'DIRECT_MESSAGES']
} // nos intents coloque oque você precisa, coloquei todos que tem, menos dois que tem que ativar no url: https://discord.com/developers/applications/IdDoSeuBOT/bot vá até gateway intens e marque as duas opções!